QuizHoot/Models/Quiz.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace QuizHoot.Models
{
    public partial class Quiz
    {
        public Quiz()
        {
            Questions = new HashSet<Question>();
            TakeQuizzes = new HashSet<TakeQuiz>();
        }

        public int QuizId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public bool Publish { get; set; }
        public DateTime? StartAt { get; set; }
        public DateTime? EndAt { get; set; }
        public int PassScore { get; set; }
        public string CreatorId { get; set; }

        public virtual AspNetUser Creator { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<TakeQuiz> TakeQuizzes { get; set; }
    }
}

QuizHoot/Models/ViewModels/QuizViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuizHoot.Models.ViewModels
{
    public class QuizViewModel
    {
        public Quiz Quiz { get; set; }
        public int PlayQuizNumber { get; set; }
        public int TotalQuestion { get; set; }
    }
}

QuizHoot/Controllers/QuizController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuizHoot.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using QuizHoot.Areas.Identity.Data;
using QuizHoot.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.SignalR;
using QuizHoot.Hubs;

namespace QuizHoot.Controllers
{
    public class QuizController : Controller
    {
        private readonly QuizHootContext _context;
        private readonly UserManager<QuizHootUser> _userManager;
        private readonly IHubContext<SignalRServer> _hubContext;
        public QuizController(QuizHootContext ctx, UserManager<QuizHootUser> userManager, IHubContext<SignalRServer> hubContext)
        {
            _context = ctx;
            _userManager = userManager;
            _hubContext = hubContext;
        }

        public IActionResult List(string txtsearch)
        {

            List<Quiz> quizzes = (txtsearch is null || txtsearch.Trim() == "")
                ? _context.Quizzes.Include(q => q.Creator).Where(q => q.Publish).ToList()
                : _context.Quizzes.Include(q => q.Creator).Where(q => q.Publish && (q.QuizId.ToString().Contains(txtsearch.ToLower())
                    || q.Title.ToLower().Contains(txtsearch.ToLower()))).ToList();


            var quizViewModels = new List<QuizViewModel>();

            foreach (var q in quizzes)
            {
                int amount = _context.TakeQuizzes.Where(tq => tq.QuizId == q.QuizId).Count();
                var qv = new QuizViewModel();
                qv.Quiz = q;
                qv.TotalQuestion = _context.Questions.Where(q => q.QuizId == qv.Quiz.QuizId).Count();
                qv.PlayQuizNumber = amount;
                quizViewModels.Add(qv);
            }

            return View(quizViewModels);
        }

        public IActionResult DoQuiz(int qid)
        {
            var user = HttpContext.User;

            if (!user.Identity.IsAuthenticated)
            {
                return Redirect("/Identity/Account/Login");
            }

            var uId = _userManager.GetUserId(user);
            var startTime = DateTime.Now;
            var quiz = _context.Quizzes.Find(qid);

            if (quiz is null) return NotFound();
            if (!quiz.Publish) return Content("Quiz is not avaiable.");
            if (quiz.StartAt is not null && startTime < quiz.StartAt)
            {
                ViewData["ErrorMessage"] = "This quiz is not started.";
                return View("ErrorPage");
            }

            if (quiz.EndAt is not null && quiz.EndAt < startTime)
            {
                ViewData["ErrorMessage"] = "The time to take this test has expired.";
                return View("ErrorPage");
            }

            TakeQuiz takeQuiz = new TakeQuiz
            {
                StartAt = DateTime.Now,
                FinishAt = null,
                Score = 0,
                QuizId = qid,
                UserId = uId
            };

            _context.TakeQuizzes.Add(takeQuiz);
            _context.SaveChanges();

            return RedirectToAction("DoQuizInProcess", new
            {
                takeQuizId = takeQuiz.TakeQuizId
            });
        }

        public IActionResult DoQuizInProcess(int takeQuizId)
        {

            var uId = _userManager.GetUserId(HttpContext.User);

            TakeQuiz takeQuiz = _context.TakeQuizzes
                .Where(tq => tq.TakeQuizId == takeQuizId && tq.UserId.Equals(uId))
                .FirstOrDefault();

            if (takeQuiz is null)
            {
                ViewData["ErrorCode"] = "404";
                ViewData["ErrorMessage"] = "PAGE NOT FOUND";
                ViewData["ErrorDescription"] = "The page you are looking for might have been removed had its name changed or is temporarily unavailable.";
                return View("ErrorPage");
            }

            var quiz = _context.Quizzes.Where(q => q.QuizId == takeQuiz.QuizId)
                .Include(q => q.Questions).ThenInclude(qs => qs.Answers).First();

            ViewBag.TakeQuiz = takeQuiz;
            return View(quiz);
        }

        [HttpPost]
        public IActionResult SubmitAnswer(List<string> selectAnswers, int takeQuizId)
        {
            var uId = _userManager.GetUserId(HttpContext.User);

            TakeQuiz takeQuiz = _context.TakeQuizzes
                .Where(tq => tq.TakeQuizId == takeQuizId && tq.UserId == uId)
                .FirstOrDefault();

            // user not start do this quiz
            if (takeQuiz is null)
            {
                ViewData["ErrorCode"] = "404";
                ViewData["ErrorMessage"] = "PAGE NOT FOUND";
                ViewData["ErrorDescription"] = "The page you are looking for might have been removed had its name changed or is temporarily unavailable.";
                return View("ErrorPage");
            }

            var quiz = _context.Quizzes.Find(takeQuiz.QuizId);

            if (quiz.EndAt is not null && quiz.EndAt < DateTime.Now)
            {
                ViewData["ErrorMessage"] = "Submit Answer Fail!";
                ViewData["ErrorDescription"] = "Time is expired";
                return View("ErrorPage");
            }

            if (takeQuiz.FinishAt is not null)
            {
                ViewData["ErrorMessage"] = "Submit Answer Fail!";
                ViewData["ErrorDescription"] = "This quiz was submited, can't resubmit.";
                return View("ErrorPage");

            }

            takeQuiz.FinishAt = DateTime.Now;
            _context.TakeQuizzes.Update(takeQuiz);

            foreach (var a in selectAnswers)
            {
                var tokens = a.Split("-");
                int questionId = int.Parse(tokens[0]);
                int answerId = int.Parse(tokens[1]);

                _context.Add(new TakeAnswer
                {
                    TakeQuizId = takeQuiz.TakeQuizId,
                    QuestionId = questionId,
                    AnswerId = answerId
                });
            }


            _context.Update(takeQuiz);
            _context.SaveChanges();
            //Only after insert answer you can caculate score
            takeQuiz.Score = caculateScore(takeQuiz.TakeQuizId);
            _context.SaveChanges();

            ViewData["ErrorMessage"] = "Submit successfully!";
            return View("ErrorPage");
        }


        public IActionResult MyQuiz()
        {
            return View();
        }

        public IActionResult Edit(int id)
        {
            ViewBag.Id = id;
            Quiz quiz = _context.Quizzes.First(s => s.QuizId == id);
            ViewBag.Quiz = quiz;
            List<Question> listQuestion = _context.Questions.Include(s => s.Level).Include(s => s.Quiz).Include(s => s.Answers).Where(s => s.QuizId == id).ToList<Question>();
            ViewBag.listQuestion = listQuestion;
            var listLevel = _context.Levels.ToList<Level>();
            ViewBag.listLevel = listLevel;
            return View();
        }
        // id is  TakeQuiz.TakeQuizID
        public IActionResult Review(int id)
        {
            TakeQuiz takeQuiz = _context.TakeQuizzes.Find(id);
            var takeAnswer = _context.TakeAnswers
                .Where(ta => ta.TakeQuizId == takeQuiz.TakeQuizId).ToList();

            var reviewModel = new ReviewQuizViewModel();
            reviewModel.TakeQuiz = takeQuiz;
            reviewModel.Quiz = _context.Quizzes.Find(takeQuiz.QuizId);
            reviewModel.Questions = _context.Questions.Include(q => q.Answers)
                .Where(q => q.QuizId == reviewModel.Quiz.QuizId)
                .ToList();

            foreach (var q in reviewModel.Questions)
            {
                foreach (var a in q.Answers)
                {
                    var ck = takeAnswer.Any(n => n.AnswerId == a.AnswerId);
                    reviewModel.ReviewAnswer.Add(a, ck);
                }


                var originalAnswers = q.Answers.Where(a => a.Correct).Select(a => a.AnswerId).OrderBy(k => k).ToList();

                var compareAnswer = takeAnswer.Where(a => a.QuestionId == q.QuestionId).
                    Select(a => a.AnswerId).OrderBy(k => k).ToList();

                bool canGetFullQuestionScore = Enumerable.SequenceEqual(originalAnswers, compareAnswer);

                reviewModel.QuestionScore[q.QuestionId] = (canGetFullQuestionScore) ? q.Score : 0;
            }

            reviewModel.TotalScore = caculateScore(id);
            return View(reviewModel);
        }

        private int caculateScore(int takeQuizId)
        {
            TakeQuiz takeQuiz = _context.TakeQuizzes.Find(takeQuizId);

            if (takeQuiz is null) throw new Exception("Not found take quiz");

            var questions = _context.Questions.Where(q => q.QuizId == takeQuiz.QuizId).Include(q => q.Answers).ToList();
            var userAnswers = _context.TakeAnswers.Where(ta => ta.TakeQuizId == takeQuizId).ToList();

            if (userAnswers.Count == 0) return 0;
            int score = 0;

            foreach (var q in questions)
            {
                var trueAnwersOfQuestion = q.Answers.Where(a => a.Correct).Select(a => a.AnswerId).OrderBy(k => k).ToList();
                var userAnswerOfQuestion = userAnswers.Where(a => a.QuestionId == q.QuestionId).Select(a => a.AnswerId).OrderBy(k => k).ToList();
                if (Enumerable.SequenceEqual(trueAnwersOfQuestion, userAnswerOfQuestion))
                {
                    score += q.Score;
                }
            }

            return score;
        }

        // Crud part
        public IActionResult Detail(int id)
        {
            Quiz quiz = _context.Quizzes.Find(id);
            return View(quiz);
        }

        [HttpPost]
        public IActionResult Create(Quiz quiz, string returnUrl)
        {

QuizHoot/Views/Shared/ErrorPage.cshtml
@{ 
    Layout = "";
}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Notice</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Passion+One:900" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="/css/errorStyle.css" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>:(</h1>
			</div>
			<h2>@ViewData["ErrorCode"] @ViewData["ErrorMessage"]</h2>
			<p>@ViewData["ErrorDescription"]</p>
			<a href="/quiz/list">home page</a>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

QuizHoot/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">identity</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Quizz</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - identity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/6.0.1/signalr.js"></script>
</body>

</html>

QuizHoot/Views/Shared/_Quiz.cshtml
@using Microsoft.AspNetCore.Identity
@using QuizHoot.Areas.Identity.Data;
@inject SignInManager<QuizHootUser> SignInManager
@inject UserManager<QuizHootUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuizHoot</title>
    <link rel="stylesheet" href="~/css/quiz-layout.css" />
    @*Bootstrap 5.0*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <div class="p-0 container-fluid">
        <div class="row">
            @*Sidenav*@
            <div class="col-3 col-md-2 bg-danger">
                <h1>Navbar</h1>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a class="btn btn-primary text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">@User.Identity.Name!</a>
                }
            </div>

            <div class="col p-0">
                <div class="d-flex row p-2">
                    <div class="col-10">
                        <div class="input-group mb-3">
                            <span class="input-group-text">
                                <i class="bi bi-search"></i>
                            </span>
                            <input type="text" class="form-control" placeholder="Search" />
                            <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Quiz Library</button>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li><a class="dropdown-item" href="#">My Quiz Library</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("List", "Quiz", new { area = "" })">
                                <button type="submit" class="btn btn-danger">Logout</button>
                            </form>
                        }
                        else
                        {
                            <a class="btn btn-primary" asp-area="Identity" asp-page="/Account/Register">Register</a>
                            <a class="btn btn-primary" asp-area="Identity" asp-page="/Account/Login">Login</a>
                        }
                    </div>

                </div>
                <main role="main" class="p-3 mx-2">
                    @RenderBody()
                </main>
            </div>
        </div>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </div>
</body>
</html>